export const mockCompanyRecords: Array<Record<string, unknown>> = [
  {
    id: "cmp-1001",
    name: "Northstar AI Systems",
    domain: "northstar.ai",
    industry: "Artificial Intelligence",
    employee_count: 180,
    annual_revenue: "$55M",
    country: "United States",
    location: "Austin, Texas",
    website: "https://northstar.ai",
    linkedin_url: "https://www.linkedin.com/company/northstar-ai",
    founded_year: 2018,
    tech_stack: ["AWS", "Snowflake", "Datadog"],
    key_contacts: ["VP Sales", "Head of RevOps"],
  },
  {
    id: "cmp-1002",
    name: "LedgerPulse",
    domain: "ledgerpulse.com",
    industry: "Fintech",
    employee_count: 320,
    annual_revenue: "$72M",
    country: "United Kingdom",
    location: "London, UK",
    website: "https://ledgerpulse.com",
    linkedin_url: "https://www.linkedin.com/company/ledgerpulse",
    founded_year: 2016,
    tech_stack: ["GCP", "Kafka", "Kubernetes"],
    key_contacts: ["Chief Revenue Officer", "Director of Partnerships"],
  },
  {
    id: "cmp-1003",
    name: "Orbit Commerce Cloud",
    domain: "orbitcommerce.io",
    industry: "E-commerce",
    employee_count: 240,
    annual_revenue: "$61M",
    country: "Canada",
    location: "Toronto, Canada",
    website: "https://orbitcommerce.io",
    linkedin_url: "https://www.linkedin.com/company/orbit-commerce-cloud",
    founded_year: 2017,
    tech_stack: ["Azure", "Redis", "PostgreSQL"],
    key_contacts: ["VP Marketing", "Head of Growth"],
  },
];

export const mockProspectRecords: Array<Record<string, unknown>> = [
  {
    id: "prs-1001",
    first_name: "Avery",
    last_name: "Sharma",
    full_name: "Avery Sharma",
    title: "VP Sales",
    company_name: "Northstar AI Systems",
    email: "avery.sharma@northstar.ai",
    country: "United States",
    location: "Austin, Texas",
    linkedin_url: "https://www.linkedin.com/in/avery-sharma",
  },
  {
    id: "prs-1002",
    first_name: "Mia",
    last_name: "Keller",
    full_name: "Mia Keller",
    title: "Head of Marketing",
    company_name: "Orbit Commerce Cloud",
    email: "mia.keller@orbitcommerce.io",
    country: "Canada",
    location: "Toronto, Canada",
    linkedin_url: "https://www.linkedin.com/in/mia-keller",
  },
  {
    id: "prs-1003",
    first_name: "Luca",
    last_name: "Bell",
    full_name: "Luca Bell",
    title: "Director of Revenue Operations",
    company_name: "LedgerPulse",
    email: "luca.bell@ledgerpulse.com",
    country: "United Kingdom",
    location: "London, UK",
    linkedin_url: "https://www.linkedin.com/in/luca-bell",
  },
];
